Add js cards
ovyunova/bookStore pull request #3
Opened 2018-12-03 21:31 UTC by ovyunova

2018-12-03 22:18 UTC, nicothin commented
Жду правок по комментам из старых PR
https://github.com/ovyunova/bookStore/pulls?q=is%3Apr+is%3Aclosed

2018-12-06 06:51 UTC, nicothin requested changes

2018-12-06 06:51 UTC, nicothin commented on contact.html
> +        <div class="form__header">
БЭМ-ошибка: нет блока form, но есть его элементы

2018-12-06 06:51 UTC, nicothin commented on contact.html
> +      <div class="contact__form">
сюда примиксуйте класс form

2018-12-06 06:51 UTC, nicothin commented on contact.html
> +        <div class="form__wrap">
див предлагаю убрать, а класс написать на теге form, который ниже

2018-12-06 06:51 UTC, nicothin commented on contact.html
> +            <div class="field-checkbox">
в такой разметке это лучше сделать тегом label, чтобы клик по тексту...

2018-12-06 06:51 UTC, nicothin commented on index.html
> +                <p class="slider__item-descr">Хочу узнать о книге больше</p>
тут ссылка

2018-12-06 06:51 UTC, nicothin commented on index.html
> +                    <img src="#" class="slider__item-img">
отступ

2018-12-06 06:51 UTC, nicothin commented on index.html
> +                    <img src="#" class="slider__item-img">
отступ

2018-12-06 06:51 UTC, nicothin commented on index.html
> +                  <p class="slider__item-subtitle">Узнайте как обучить персонал с новой книгой «Пятая дисциплина»</p>
отступ

2018-12-06 06:51 UTC, nicothin commented on index.html
> +                      <img src="#" class="slider__item-img">
отступ

2018-12-06 06:51 UTC, nicothin commented on index.html
> +        <div class="catalog__paginator">
пагинацию всегда делайте БЭМ-блоком
можно примиксовать класс элемента от блока каталога, да.

2018-12-06 06:51 UTC, nicothin commented on index.html
> +        <img src="#" alt="Иконка книги">
отступ
img не нужен )

2018-12-06 06:51 UTC, nicothin commented on index.html
> +          </div>
отступ

2018-12-06 06:51 UTC, nicothin commented on index.html
> +          </div>
отступ

2018-12-06 06:51 UTC, nicothin commented on index.html
> +        <div class="advice__header-title">Наши новинки</div>
это h2

2018-12-06 06:51 UTC, nicothin commented on index.html
> +        <div class="advice__header-link"><a href="#">Все новинки</a></div>
это ссылка и только
класс дива — на ссылке должен быть

2018-12-06 06:51 UTC, nicothin commented on index.html
> +          <div class="advice-card-mini">
это тот же БЭМ-блок, что в каталоге выше
сейчас у вас это `products-card-mini`
но я бы использовал `product-card-mini`

2018-12-06 06:51 UTC, nicothin commented on index.html
> +        document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
отступ

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +     <title>Book Store - Карточка товара</title>
отступ

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +        document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
отступ

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +        <img src="#" alt="Обложка книги Супер-потребители">
отступ

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +          <ul class="product__list">
этот элемент должен соседствовать с оберткой картинки
на этом элементе пишите класс product__pages-preview

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +            <li class="product__item"><a href="#"><img src="#" alt="Картинка страницы кники"></a></li>
product__pages-preview-item

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +            <input type="number" class="field-text__input" value="20">
value="1"

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +          <span class="field-text__descr">шт</span>
это д.б. внутри обёртки инпута

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +        <p class="product__likes-numbers">20 людям понравилось</p>
это д.б. внутри формы

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +        <div class="product__descr-title">Короткое описание</div>
h2

2018-12-06 06:51 UTC, nicothin commented on item-page.html
> +    <section class="advice">
комментил про этот блок выше

2018-12-06 06:51 UTC, nicothin commented on js/modules/booksCardTemplate.js
> +  tagClass: 'products-card-mini',
product-card-mini

2018-12-06 06:51 UTC, nicothin commented on js/modules/booksCardTemplate.js
> +  tag: 'div',
это article

2018-12-06 06:51 UTC, nicothin commented on js/modules/insertElement.js
> +
пустые строки в начале файла убрать

2018-12-06 06:51 UTC, nicothin commented on js/script.js
> +
пустые строки и закомменченный фрагмент убрать

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +<!DOCTYPE html>
в именах файлов старайтесь не использовать сокращения

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +          <p class="recommendation__foto-title">Наши подборки ваших лучших фотографий у нас</p>
вероятно, весь блок является ссылкой

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +        <div class="recommendation__book">
вероятно, весь блок является ссылкой

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +          <button class="btn">Проголосовать</button>
скорее, ссылка на страницу голосования
не критично

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +        <div class="recommendation__news">
вероятно, весь блок является ссылкой

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +        <div class="recommendation__old">
вероятно, весь блок является ссылкой

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +      <div class="advice__header">
вероятно, весь блок является ссылкой

не ясно откуда advice взялся в классе
БЭМ-ошибка

2018-12-06 06:51 UTC, nicothin commented on recomm.html
> +      <div class="advice__list-wrap">
нет
здесь д.б. карточка товара, такая же, как в каталоге на главной

2018-12-06 06:51 UTC, nicothin commented on test.html
> +<!DOCTYPE html>
лишний файл.
убить.

2018-12-06 06:51 UTC, nicothin commented on untitled.json
> +
вероятно, лишний файл
убить.

2018-12-06 19:19 UTC, ovyunova commented on recomm.html
> +<!DOCTYPE html>
Я могу переименовать файл? А потом запушить? файл перезапишется на гите?

2018-12-06 19:30 UTC, ovyunova commented on recomm.html
> +      <div class="advice__list-wrap">
Он взялся потому, что пересекаются классы. На странице товара у меня целый блок продукт. тогда получается нужно переписать или этот блок или пол страницы товар....

2018-12-07 11:18 UTC, nicothin commented on recomm.html
> +      <div class="advice__list-wrap">
что пересекается?
на странице товара — `product`
на главной в каталоге `products-card-mini`
тут должен быть `products-card-mini`

2018-12-07 11:25 UTC, nicothin requested changes

2018-12-07 11:25 UTC, nicothin commented on index.html
> +        <div class="catalog__paginator">
не сделано

2018-12-07 11:25 UTC, nicothin commented on item-page.html
> +        <p class="product__likes-numbers">20 людям понравилось</p>
отступ

2018-12-07 11:25 UTC, nicothin commented on item-page.html
> +        <div class="product__descr-social social-module">
вообще говоря, слова block и modile мы в именах класса обычно не используем за ненадобностью.
тут я бы тоже убрал слово module.

2018-12-07 11:25 UTC, nicothin commented on item-page.html
> +                <img src="#" class="advice-card-mini__img" alt="Картинка новинки">
отступ

2018-12-07 11:25 UTC, nicothin commented on js/modules/booksCardTemplate.js
> +  tagClass: 'products-card-mini',
не исправлено

2018-12-07 11:25 UTC, nicothin commented on js/modules/createElement.js
> +    const article = document.createElement(template.tag);
отступ

2018-12-07 11:25 UTC, nicothin commented on recommendation.html
> +          <button class="btn">Проголосовать</button>
кнопок в ссылке и ссылок в кнопке быть не должно
это ссылка, обертка — див

2018-12-07 11:25 UTC, nicothin commented on recommendation.html
> +        <a href="#" class="recommendation__blog">
див

2018-12-07 11:25 UTC, nicothin commented on recommendation.html
> +          <p class="recommendation__blog-link">Читать статью</p>
ссылка

2018-12-07 11:25 UTC, nicothin commented on recommendation.html
> +          <div class="advice-card-mini">
это тот же Блок, что в каталоге на главной

2018-12-07 11:25 UTC, nicothin commented on recommendation.html
> +                <img src="#" class="advice-card-mini__img" alt="Картинка новинки">
отступ )

2018-12-11 08:57 UTC, nicothin approved these changes
Микроисправление мною же внесенного бага и можно вливать в мастер ))

2018-12-11 08:57 UTC, nicothin commented on index.html
> +          <div class="catalog__list j-cards">
по-хорошему сюда потом (когда доверстаете макет) стоит впилить БЭМ-блок `loader` с каким-то крутящимся элементом.

2018-12-11 08:57 UTC, nicothin commented on index.html
> +      <div class="additionls__header">
чёрт, я тут, когда правил, допустил опечатку :(
замените пожалуйста в классах элементов: `additionls` → `additionals`

2018-12-11 09:21 UTC, nicothin commented
И да, наверное, `import data from './modules/booksData.js';` не нужен, раз уж с сервера получаете данные о книгах.

2018-12-12 22:26 UTC, nicothin commented
Вливайте.
И начинайте стилизацию главной.

2018-12-12 23:33 UTC, merged